<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Aa</name>
   <tag></tag>
   <elementGuidId>ddea85d5-aa1a-4500-bfad-a5bbc8770974</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/main/div/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Aa&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>164946a3-d4b6-4313-ba81-688cafba149b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-current</name>
      <type>Main</type>
      <value>page</value>
      <webElementGuid>f1902ac3-7dd8-4098-b94b-835d02dbab1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>navigation_active__R+RSM active</value>
      <webElementGuid>b5488967-80ce-4e30-9cea-b4f58d980fa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/penta-app-admin-entry-point/BeeFlow/ProjectManagement/2c9180a997a820ca019828528e270a3f/BasicInformation</value>
      <webElementGuid>add0e19a-3757-435a-b527-8a1ac07de2f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aa</value>
      <webElementGuid>ad173b3d-94dd-4a0e-a2f6-5cd3bcf532ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App d-flex flex-column&quot;]/main[@class=&quot;layout_layout-container__SwD1Y&quot;]/div[@class=&quot;navigation_nav-items-container__XZDz8&quot;]/ul[@class=&quot;navigation_nav-items-list-container__w1vn2&quot;]/li[@class=&quot;navigation_main-nav-items__JSR-T&quot;]/a[@class=&quot;navigation_active__R+RSM active&quot;]</value>
      <webElementGuid>07cb258c-bc99-4f52-a924-2ce7fb93b6d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/ul/li[2]/a</value>
      <webElementGuid>62f221b4-b0fc-4710-bc2c-c6930293316f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English'])[2]/following::a[1]</value>
      <webElementGuid>6d7b755e-4b5c-4ac0-ab4f-fa901b124df2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Out'])[1]/following::a[1]</value>
      <webElementGuid>a859163a-3e08-4b1f-a2bf-8b6e33aaeada</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Process management'])[1]/preceding::a[1]</value>
      <webElementGuid>b084aa2a-04d8-4e8e-8474-7016f85607ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/penta-app-admin-entry-point/BeeFlow/ProjectManagement/2c9180a997a820ca019828528e270a3f/BasicInformation')]</value>
      <webElementGuid>c66addd9-a90b-4d3a-becc-86e67148ab6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/ul/li[2]/a</value>
      <webElementGuid>41475124-585d-4196-9d3a-4434a79379f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/penta-app-admin-entry-point/BeeFlow/ProjectManagement/2c9180a997a820ca019828528e270a3f/BasicInformation' and (text() = 'Aa' or . = 'Aa')]</value>
      <webElementGuid>82656bad-aeed-4a62-bef4-78fd53aaddbe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
