<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_My Contributions_common-nav__link-contrib_5eb766</name>
   <tag></tag>
   <elementGuidId>2885d126-a370-4d52-a781-16006ef46994</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='common-nav__link-contrib-plugin-catalogue']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#common-nav__link-contrib-plugin-catalogue</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Plugins&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>446d3246-2834-4699-bd7d-275e8f36afa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item MobileNav_dropdown-item__05t37</value>
      <webElementGuid>fb916baf-f285-4fe7-b983-2feab6e2842b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>common-nav__link-contrib-plugin-catalogue</value>
      <webElementGuid>5036ccdb-7784-49f3-94bb-6c684bc41429</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/penta-app-admin-entry-point-fb/MnA-fb/MyContributionsPlugins</value>
      <webElementGuid>9a78041a-0e9f-45da-8ecc-577fbca7f6dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Plugins</value>
      <webElementGuid>b06ac5f7-6f36-451d-9bad-b4ec137dbdba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;common-nav__link-contrib-plugin-catalogue&quot;)</value>
      <webElementGuid>7dcdc739-41e7-4985-b986-094c5a841b4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='common-nav__link-contrib-plugin-catalogue']</value>
      <webElementGuid>9f3b4bcf-79be-41c7-9728-1fbe465c190e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarSupportedContent']/div/ul/li[5]/ul/a</value>
      <webElementGuid>05d02ecb-b062-4397-b08c-edbb22c1464f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Plugins')])[2]</value>
      <webElementGuid>1b954be4-93e5-494d-992a-9eb71619874b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Contributions'])[1]/following::a[1]</value>
      <webElementGuid>b4e0295b-ed82-4849-a817-a781ad5cbd36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Applications Catalogue'])[1]/following::a[2]</value>
      <webElementGuid>4fa4f194-3f25-4c08-91cf-1f983f572cef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Applications'])[1]/preceding::a[1]</value>
      <webElementGuid>c5296e3f-f56a-4ca7-9e2f-167df9d12761</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sheets'])[2]/preceding::a[2]</value>
      <webElementGuid>a05c88e1-95e1-4826-b6c5-9777b825e5c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/penta-app-admin-entry-point-fb/MnA-fb/MyContributionsPlugins')]</value>
      <webElementGuid>b4c0ca95-2c57-47ce-9ec8-aa164d4483d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/ul/a</value>
      <webElementGuid>21c86db2-bacc-4feb-a372-9d34a4dc5a6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'common-nav__link-contrib-plugin-catalogue' and @href = '/penta-app-admin-entry-point-fb/MnA-fb/MyContributionsPlugins' and (text() = 'Plugins' or . = 'Plugins')]</value>
      <webElementGuid>0fc8e03e-aeb6-4285-a177-4db5f2371a7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
