<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Plugins</name>
   <tag></tag>
   <elementGuidId>140a0f76-cf7f-4cde-a0ea-04ece91afc4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='common-nav__link-contrib-plugin-catalogue']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#common-nav__link-contrib-plugin-catalogue</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Plugins&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>07a3c948-47f6-4659-8b28-bac9e8adf268</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item MobileNav_dropdown-item__05t37</value>
      <webElementGuid>90fd69d6-0961-4e67-9d96-a9c97dfc99b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>common-nav__link-contrib-plugin-catalogue</value>
      <webElementGuid>f6730743-c47b-4c46-8d52-813050bc70a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/penta-app-admin-entry-point-fb/MnA-fb/MyContributionsPlugins</value>
      <webElementGuid>3e1242a2-aaaf-43fd-b329-90fc2b088f96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Plugins</value>
      <webElementGuid>269f6c4b-f50d-4c0d-849d-28ac59a3db91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;common-nav__link-contrib-plugin-catalogue&quot;)</value>
      <webElementGuid>53854dbb-f119-4c2d-880d-13a4ab5ec41b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='common-nav__link-contrib-plugin-catalogue']</value>
      <webElementGuid>356d1c11-ec24-4a6c-a908-9e5232b60f22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarSupportedContent']/div/ul/li[5]/ul/a</value>
      <webElementGuid>3993519c-e1c5-4fd5-b35c-d26497b21080</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Plugins')])[2]</value>
      <webElementGuid>322c529d-607e-4da6-8666-5767c1b3ce66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Contributions'])[1]/following::a[1]</value>
      <webElementGuid>64635df2-bd9f-4b9a-a429-7e209288d302</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Applications Catalogue'])[1]/following::a[2]</value>
      <webElementGuid>6afab801-657d-4242-a888-acbe7659d786</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Applications'])[1]/preceding::a[1]</value>
      <webElementGuid>f35e0a94-d7b6-47b4-9c16-35e31e9a5ee8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sheets'])[2]/preceding::a[2]</value>
      <webElementGuid>9a9c42bd-cd45-4f27-81bd-973e918c330c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/penta-app-admin-entry-point-fb/MnA-fb/MyContributionsPlugins')]</value>
      <webElementGuid>e9ca7679-a3d7-49b7-af08-a534cd8dd07d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/ul/a</value>
      <webElementGuid>3a67082d-a619-4df0-893c-b27159f628d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'common-nav__link-contrib-plugin-catalogue' and @href = '/penta-app-admin-entry-point-fb/MnA-fb/MyContributionsPlugins' and (text() = 'Plugins' or . = 'Plugins')]</value>
      <webElementGuid>c22c41cb-9065-47e1-a882-3c56301d25a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
