<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Plugins</name>
   <tag></tag>
   <elementGuidId>140a0f76-cf7f-4cde-a0ea-04ece91afc4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='common-nav__link-contrib-plugin-catalogue']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#common-nav__link-contrib-plugin-catalogue</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Plugins&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>09417b3a-b6a0-49b8-8655-5bfcd87184bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item MobileNav_dropdown-item__05t37</value>
      <webElementGuid>ddb7d170-cdae-436a-bfc8-41e7e650f50c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>common-nav__link-contrib-plugin-catalogue</value>
      <webElementGuid>530386e4-a2b9-4755-a9d4-8d5c5caafc44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/penta-app-admin-entry-point-fb/MnA-fb/MyContributionsPlugins</value>
      <webElementGuid>21b5c460-acee-489a-a99b-6125be230536</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Plugins</value>
      <webElementGuid>7172bcaf-5c4b-43d1-b32a-2497eea24310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;common-nav__link-contrib-plugin-catalogue&quot;)</value>
      <webElementGuid>f9f33ee0-8b2d-47d1-9158-63b29a360163</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='common-nav__link-contrib-plugin-catalogue']</value>
      <webElementGuid>bda36f21-fdae-43b0-b339-971106028f5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarSupportedContent']/div/ul/li[5]/ul/a</value>
      <webElementGuid>db261cad-da0d-42e6-a60d-ab6ee10d4fc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Plugins')])[2]</value>
      <webElementGuid>f06d20fb-2a55-4227-af13-09a69d32b133</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Contributions'])[1]/following::a[1]</value>
      <webElementGuid>7416e720-bd4e-4f19-ab8d-dda6d71bd54e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Applications Catalogue'])[1]/following::a[2]</value>
      <webElementGuid>21d87c66-72c4-457a-a3f1-2db8ab007a9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Applications'])[1]/preceding::a[1]</value>
      <webElementGuid>3ec153be-9291-44c5-938e-e23ac3bcaffa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sheets'])[2]/preceding::a[2]</value>
      <webElementGuid>68f590c2-19ec-443f-8858-eafa28ddf0e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/penta-app-admin-entry-point-fb/MnA-fb/MyContributionsPlugins')]</value>
      <webElementGuid>d384579e-f012-4386-af54-c76272409de5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/ul/a</value>
      <webElementGuid>292b70db-b1b9-4075-9fbb-f44cf6bc8ee9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'common-nav__link-contrib-plugin-catalogue' and @href = '/penta-app-admin-entry-point-fb/MnA-fb/MyContributionsPlugins' and (text() = 'Plugins' or . = 'Plugins')]</value>
      <webElementGuid>13a0963f-88fc-4aea-a2d7-99e17f6d922c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
