<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Layers</name>
   <tag></tag>
   <elementGuidId>e160ec35-1131-4258-a331-4273674b8320</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='navbar']/div/div/div[2]/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#navbar div >> internal:has-text=/^Layers$/ >> nth=2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1f6fa5c6-8cfa-46de-9688-1c56ac33ca90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>NavSearch_select-dropdown__9qxq+</value>
      <webElementGuid>6fa469f0-eb04-4472-be22-e04b60cabad0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Layers</value>
      <webElementGuid>7f2debe6-3f17-4e71-859a-996a6c33cb61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbar&quot;)/div[1]/div[@class=&quot;container-fluid Header_nav-search__vQqJ8&quot;]/div[@class=&quot;Header_left-side__El71I&quot;]/div[@class=&quot;NavSearch_select-search__+AZ7m undefined&quot;]/div[@class=&quot;NavSearch_select-dropdown__9qxq+&quot;]</value>
      <webElementGuid>22f08419-efc8-42fd-a906-113f63be57a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='navbar']/div/div/div[2]/div/div[2]</value>
      <webElementGuid>8ad0d618-d656-45a1-a31c-3cfecec9a547</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English'])[1]/following::div[9]</value>
      <webElementGuid>1e299ce8-19d4-4847-a239-825c425078b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MnA is not optimized for Mobile use and best fit for Desktop view only'])[1]/following::div[31]</value>
      <webElementGuid>84265c84-60fe-4610-a668-f6ea6a94f6fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[2]/preceding::div[3]</value>
      <webElementGuid>aa52118a-66e7-4155-9e5e-f481facfcd30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]</value>
      <webElementGuid>3d9cfaf5-1801-4452-a277-7f1523bf19df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Layers' or . = 'Layers')]</value>
      <webElementGuid>5d07e49a-16ea-4548-ac61-efe50718ddec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
