<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Coded Lists_nav-link MobileNav_nav-dropdo_c36666</name>
   <tag></tag>
   <elementGuidId>743bfc08-20e5-41d3-b681-4e3006db38d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navbarSupportedContent']/div/ul/li[7]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Developers&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>70306d4d-6d76-4481-b477-53366b09ea5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link MobileNav_nav-dropdown__slkNU MobileNav_nav-link__cOsQ6 false </value>
      <webElementGuid>159d81fd-dc44-4348-a301-8addbd16f3a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Developers</value>
      <webElementGuid>2eb71183-089c-451f-b9ea-f316adeae72e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbar&quot;)/div[1]/div[@id=&quot;navbarSupportedContent&quot;]/div[@class=&quot;container-fluid MobileNav_nav-container__815-D&quot;]/ul[@class=&quot;navbar-nav MobileNav_navbar-nav__dQ3SV&quot;]/li[@class=&quot;nav-item dropdown MobileNav_nav-dropdown-container__ROJVx&quot;]/a[@class=&quot;nav-link MobileNav_nav-dropdown__slkNU MobileNav_nav-link__cOsQ6 false&quot;]</value>
      <webElementGuid>1741a2eb-e65f-406e-bfc7-95af9f02c47f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarSupportedContent']/div/ul/li[7]/a</value>
      <webElementGuid>65d55d73-1c33-4c90-8940-7b1edec15723</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Developers')]</value>
      <webElementGuid>ed28ca9b-7423-42b9-8f72-da94cb14c79a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coded Lists'])[3]/following::a[1]</value>
      <webElementGuid>dd27d8b9-be5f-4e18-8311-564e24560dc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Layers'])[4]/following::a[2]</value>
      <webElementGuid>1954c249-5fd7-46c3-be56-94b7c972edc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Plugin Configurator'])[1]/preceding::a[1]</value>
      <webElementGuid>884b72a1-2ed7-4ec9-b85b-6379b8fd093f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Explorer'])[1]/preceding::a[2]</value>
      <webElementGuid>4b9a971a-c86e-44da-93f4-c31900d8846d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Developers']/parent::*</value>
      <webElementGuid>d1a3e777-05ba-42f8-a006-71cf24b6ea71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/a</value>
      <webElementGuid>dca37100-d8be-4c9b-8ed6-96c7f326e50d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Developers' or . = 'Developers')]</value>
      <webElementGuid>c14ab0d7-de04-4063-84a2-ba46a90798bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
