<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Fallback_container__fWICT suspense-load_fb2d3a</name>
   <tag></tag>
   <elementGuidId>4bd8ff8f-1826-41fa-8dfb-eaeeed0b13cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6264d723-8ab7-4908-a208-28ce5c2fc30b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Fallback_container__fWICT suspense-loader d-flex justify-content-center align-items-center</value>
      <webElementGuid>c0b5a38e-d01a-4223-bba9-6c20fda86972</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[@class=&quot;Fallback_container__fWICT suspense-loader d-flex justify-content-center align-items-center&quot;]</value>
      <webElementGuid>09fff365-216e-4ba1-9454-03201c847d4d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
