<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Fields_clientSideSearch-module__searc_a48355_5</name>
   <tag></tag>
   <elementGuidId>12df80f0-2947-462b-a73f-f1b676197c0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.container-module__container--s5FMn.container-module__container--column--_uXCG.formDesignerFields-module__form-designer-field__container--VHoV9.formDesignerFields-module__hovered--J5m_t > div.container-module__container__header--cknVj.formDesignerFields-module__form-designer-field__container__header--B3HYr > div.clientSideSearch-module__search__container--da0A_.formDesignerFields-module__form-designer-field__container__header__search-container--HKhFz > div.ClientSideTextFilter-module__filter-section--s5hwE > div.ClientSideTextFilter-module__search-section--TpaRB > input.clientSideSearch-module__search__input--MNLQK</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='numbe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c04646f0-460a-41c0-b3fc-dcd94a920bf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a13f322f-1cb0-41a7-9c1c-f39573d94a6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search for fields</value>
      <webElementGuid>8f9f4002-98a0-4b30-9492-6a708e7a4706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>clientSideSearch-module__search__input--MNLQK</value>
      <webElementGuid>179767da-9dbd-4281-ad59-3710537faacb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>numbe</value>
      <webElementGuid>f1fcb0a7-510f-4e30-b1b9-f244d35d0118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;ltr&quot;]/div[2]/div[@class=&quot;modal-dialog modal-dialog-centered mx-auto PluginConfiguratorModal_configurator-modal__pHbBU&quot;]/div[@class=&quot;modal-content Modal_modal__rPrIC&quot;]/div[@class=&quot;modal-body Modal_modal-body__GZVHS&quot;]/div[@class=&quot;row&quot;]/div[1]/div[@class=&quot;Configurator_configurator-container__6SRJm&quot;]/div[1]/div[@class=&quot;Configurator_nested-tabs__OaaCo&quot;]/div[1]/div[@class=&quot;Configurator_overlay-container__wTRRa&quot;]/section[@class=&quot;layout-module__layout--X_ghC&quot;]/section[@class=&quot;layout-module__layout__from-designer-fields--VdORR layout-module__global-styles--QBg5e&quot;]/div[@class=&quot;container-module__container--s5FMn container-module__container--column--_uXCG formDesignerFields-module__form-designer-field__container--VHoV9 formDesignerFields-module__hovered--J5m_t&quot;]/div[@class=&quot;container-module__container__header--cknVj formDesignerFields-module__form-designer-field__container__header--B3HYr&quot;]/div[@class=&quot;clientSideSearch-module__search__container--da0A_ formDesignerFields-module__form-designer-field__container__header__search-container--HKhFz&quot;]/div[@class=&quot;ClientSideTextFilter-module__filter-section--s5hwE&quot;]/div[@class=&quot;ClientSideTextFilter-module__search-section--TpaRB&quot;]/input[@class=&quot;clientSideSearch-module__search__input--MNLQK&quot;]</value>
      <webElementGuid>418d29e3-cd11-4818-ac6b-bd78d0a1ed3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='numbe']</value>
      <webElementGuid>c3684a6d-1fcc-4635-92f5-b0eb436aa26d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/div/div[2]/section/section/div/div/div/div/div/input</value>
      <webElementGuid>bd355664-dc7e-4a7b-b97a-c4e2aba7acea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Search for fields']</value>
      <webElementGuid>3ec7db1e-8053-46e1-91b2-bd99e03063f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
