<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Fields_clientSideSearch-module__searc_a48355_2</name>
   <tag></tag>
   <elementGuidId>04dce641-f5ea-41e6-a6d9-f2d35becad94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.container-module__container--s5FMn.container-module__container--column--_uXCG.formDesignerFields-module__form-designer-field__container--VHoV9.formDesignerFields-module__hovered--J5m_t > div.container-module__container__header--cknVj.formDesignerFields-module__form-designer-field__container__header--B3HYr > div.clientSideSearch-module__search__container--da0A_.formDesignerFields-module__form-designer-field__container__header__search-container--HKhFz > div.ClientSideTextFilter-module__filter-section--s5hwE > div.ClientSideTextFilter-module__search-section--TpaRB > input.clientSideSearch-module__search__input--MNLQK</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='nu']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Search for fields&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5439844c-f72b-48bf-b8af-8d2211f4e5ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3c6f3cde-cf70-420d-9484-ef67f295b243</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search for fields</value>
      <webElementGuid>ee8d8a4e-5d67-4fbd-a73f-9c5f753a198b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>clientSideSearch-module__search__input--MNLQK</value>
      <webElementGuid>5ebe749e-f5aa-4aff-bb08-9e3b2511ad71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>nu</value>
      <webElementGuid>4b0a08b6-1923-4b5f-8a4d-9586ab55ae2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;ltr&quot;]/div[2]/div[@class=&quot;modal-dialog modal-dialog-centered mx-auto PluginConfiguratorModal_configurator-modal__pHbBU&quot;]/div[@class=&quot;modal-content Modal_modal__rPrIC&quot;]/div[@class=&quot;modal-body Modal_modal-body__GZVHS&quot;]/div[@class=&quot;row&quot;]/div[1]/div[@class=&quot;Configurator_configurator-container__6SRJm&quot;]/div[1]/div[@class=&quot;Configurator_nested-tabs__OaaCo&quot;]/div[1]/div[@class=&quot;Configurator_overlay-container__wTRRa&quot;]/section[@class=&quot;layout-module__layout--X_ghC&quot;]/section[@class=&quot;layout-module__layout__from-designer-fields--VdORR layout-module__global-styles--QBg5e&quot;]/div[@class=&quot;container-module__container--s5FMn container-module__container--column--_uXCG formDesignerFields-module__form-designer-field__container--VHoV9 formDesignerFields-module__hovered--J5m_t&quot;]/div[@class=&quot;container-module__container__header--cknVj formDesignerFields-module__form-designer-field__container__header--B3HYr&quot;]/div[@class=&quot;clientSideSearch-module__search__container--da0A_ formDesignerFields-module__form-designer-field__container__header__search-container--HKhFz&quot;]/div[@class=&quot;ClientSideTextFilter-module__filter-section--s5hwE&quot;]/div[@class=&quot;ClientSideTextFilter-module__search-section--TpaRB&quot;]/input[@class=&quot;clientSideSearch-module__search__input--MNLQK&quot;]</value>
      <webElementGuid>137915f4-6626-4451-be2f-28f8cbc17a21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='nu']</value>
      <webElementGuid>b95b410b-c655-4dcd-b603-2add45590e75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/div/div[2]/section/section/div/div/div/div/div/input</value>
      <webElementGuid>1c747531-1213-4222-a853-72d0fd378534</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Search for fields']</value>
      <webElementGuid>b3bf7ee6-e747-4ec3-8b3a-8a84b5b703f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
