<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Fields_clientSideSearch-module__searc_a48355_4</name>
   <tag></tag>
   <elementGuidId>f79c0091-7a4f-490b-8604-945ad29210c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.container-module__container--s5FMn.container-module__container--column--_uXCG.formDesignerFields-module__form-designer-field__container--VHoV9.formDesignerFields-module__hovered--J5m_t > div.container-module__container__header--cknVj.formDesignerFields-module__form-designer-field__container__header--B3HYr > div.clientSideSearch-module__search__container--da0A_.formDesignerFields-module__form-designer-field__container__header__search-container--HKhFz > div.ClientSideTextFilter-module__filter-section--s5hwE > div.ClientSideTextFilter-module__search-section--TpaRB > input.clientSideSearch-module__search__input--MNLQK</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='numb']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Search for fields&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e2bb2d6a-535b-4b15-8569-ab1cbf297ff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b7377d04-1966-48b2-a0ec-c19c9240965d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search for fields</value>
      <webElementGuid>02e911b4-9ae3-41dc-aaaa-b06111cb8fa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>clientSideSearch-module__search__input--MNLQK</value>
      <webElementGuid>7fd89a1d-217a-4860-93cf-a039ca0c6437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>numb</value>
      <webElementGuid>39c7ada0-21f6-4e0e-9725-84fd3777744b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;ltr&quot;]/div[2]/div[@class=&quot;modal-dialog modal-dialog-centered mx-auto PluginConfiguratorModal_configurator-modal__pHbBU&quot;]/div[@class=&quot;modal-content Modal_modal__rPrIC&quot;]/div[@class=&quot;modal-body Modal_modal-body__GZVHS&quot;]/div[@class=&quot;row&quot;]/div[1]/div[@class=&quot;Configurator_configurator-container__6SRJm&quot;]/div[1]/div[@class=&quot;Configurator_nested-tabs__OaaCo&quot;]/div[1]/div[@class=&quot;Configurator_overlay-container__wTRRa&quot;]/section[@class=&quot;layout-module__layout--X_ghC&quot;]/section[@class=&quot;layout-module__layout__from-designer-fields--VdORR layout-module__global-styles--QBg5e&quot;]/div[@class=&quot;container-module__container--s5FMn container-module__container--column--_uXCG formDesignerFields-module__form-designer-field__container--VHoV9 formDesignerFields-module__hovered--J5m_t&quot;]/div[@class=&quot;container-module__container__header--cknVj formDesignerFields-module__form-designer-field__container__header--B3HYr&quot;]/div[@class=&quot;clientSideSearch-module__search__container--da0A_ formDesignerFields-module__form-designer-field__container__header__search-container--HKhFz&quot;]/div[@class=&quot;ClientSideTextFilter-module__filter-section--s5hwE&quot;]/div[@class=&quot;ClientSideTextFilter-module__search-section--TpaRB&quot;]/input[@class=&quot;clientSideSearch-module__search__input--MNLQK&quot;]</value>
      <webElementGuid>3db0cd3d-a2a4-49ae-b5e5-4e916a92e35f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='numb']</value>
      <webElementGuid>829819c2-f899-4428-afbf-35e1b29b46b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/div/div[2]/section/section/div/div/div/div/div/input</value>
      <webElementGuid>ea4595d0-c2d6-4f1a-a527-7df6f8bf5e47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Search for fields']</value>
      <webElementGuid>03846695-ee9e-48a6-b7f8-eaf42dcdbec6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
