<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_c</name>
   <tag></tag>
   <elementGuidId>4b980781-e576-49c6-8081-831382cc0941</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.sharedCardTitle_shared-card-title__8K4hh</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div[2]/div/div/div/div/div[2]/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;c&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>278f2e81-d872-4c32-936a-9c887cdfd360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sharedCardTitle_shared-card-title__8K4hh</value>
      <webElementGuid>08b4781f-bd34-4210-bf55-3ab8326d258e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>c</value>
      <webElementGuid>d651c681-56e9-49cd-aa56-7a1665827640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>c</value>
      <webElementGuid>ddddefe6-4014-4b27-8db2-73834e52bb99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App d-flex flex-column&quot;]/div[@class=&quot;projectManagement_project-catalogue-container__1tNol&quot;]/div[@class=&quot;sharedCatalogueBase_shared-catalogue-base-container__WV0S1&quot;]/div[@class=&quot;d-flex gap-3 flex-wrap&quot;]/div[@class=&quot;LocalGridCatalog-module__local-card--_Tkjr projectManagement_project-catalogue-card__TK1m3&quot;]/div[@class=&quot;GridCard-module__card--K7_7f projectCard_project-card__1SBUw d-flex p-3 flex-column&quot;]/div[@class=&quot;d-flex gap-3 flex-column flex-grow-1&quot;]/div[@class=&quot;d-flex flex-column gap-2&quot;]/div[@class=&quot;d-flex gap-2 justify-content-between&quot;]/div[@class=&quot;sharedCardTitle_shared-card-title-container__y7FDe&quot;]/div[@class=&quot;sharedCardTitle_shared-card-title__8K4hh&quot;]</value>
      <webElementGuid>dc3cad09-276e-4735-958b-98743181df78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div/div/div/div/div[2]/div/div/div</value>
      <webElementGuid>ad07798b-85f7-4207-9609-f19dd90fe842</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create new project'])[1]/following::div[12]</value>
      <webElementGuid>5a8e37ca-cb2b-48d5-905e-a9cb906aed2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Import Project'])[1]/following::div[14]</value>
      <webElementGuid>4cb9efb7-284e-4eb8-9fcb-00f781b99c66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='des'])[1]/preceding::div[2]</value>
      <webElementGuid>93bdb2ad-a542-4a45-9bb2-6c4cd8370ddf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Full Preview'])[1]/preceding::div[4]</value>
      <webElementGuid>3e8a6755-49c9-42d2-b871-7b3a7c305b99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='c']/parent::*</value>
      <webElementGuid>0b32afd6-89f3-41f2-98a0-7148c21627cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/div[2]/div/div/div</value>
      <webElementGuid>053f5d2d-c909-475c-8cf6-f5c2a18df173</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@title = 'c' and (text() = 'c' or . = 'c')]</value>
      <webElementGuid>0e33e771-19e3-4380-84c5-4232907c42ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
