<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Organization Name_login-form__input-org-name</name>
   <tag></tag>
   <elementGuidId>4e030419-2997-4113-b46e-525c2979a031</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#login-form__input-org-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='login-form__input-org-name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Organization Name&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>69d085d6-219b-40e1-b050-07946e7ebf04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login-form__input-org-name</value>
      <webElementGuid>7ad936ea-3bd5-4b94-9f58-f47b3a1d0318</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f7c04886-0290-49bd-9121-b10c2e498459</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TextFieldInput_text-input__N7FVO RegisterOrg_register-input__of6X9</value>
      <webElementGuid>eebb414c-c614-42e0-9e91-0f184adfe082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Organization Name</value>
      <webElementGuid>6516aa1e-809e-444e-bdc3-28317399daae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2d3dc8a6-1a2a-4964-b646-8f4541291cfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>b3087048-507b-40b8-b94f-ddcc2dad3695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-form__input-org-name&quot;)</value>
      <webElementGuid>edbc1c9b-f656-4a25-9d14-978f62ebcff4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='login-form__input-org-name']</value>
      <webElementGuid>4a16da60-894f-40f0-a002-78eb60aa4bee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>354f5443-d007-402d-8f89-e39a5351f584</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>88941ca9-f6f9-47b3-a300-63e6e086bd04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'login-form__input-org-name' and @type = 'text' and @placeholder = 'Organization Name']</value>
      <webElementGuid>6149ecf8-a476-42b1-9ecc-07289701d736</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
