<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__selectedOrg</name>
   <tag></tag>
   <elementGuidId>b29c1f08-756a-48bf-b310-ab8737407089</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;selectedOrg&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='selectedOrg']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;ادخل اسم المنظمة&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e68a7c07-5cbd-4d72-8440-b19217ab8629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>selectedOrg</value>
      <webElementGuid>4871da83-eb75-45ed-8f01-c132018f773d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>32d87048-2120-4dbc-a645-6dd6051cd19b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>ادخل اسم المنظمة</value>
      <webElementGuid>b8a6d8e9-b846-443d-8a7b-434aa88fe1a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;lgn&quot;]/div[@class=&quot;login-form&quot;]/form[@class=&quot;login&quot;]/input[1]</value>
      <webElementGuid>0d48e1cb-a3a5-4de1-8137-5354102adc03</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='selectedOrg']</value>
      <webElementGuid>633f9241-6dcf-4ef0-a7c2-9d8976617b1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='root']/div/div/div/form/input</value>
      <webElementGuid>707e011f-ab9b-42e3-acc0-27fa4be32230</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>2e2d83e0-a55b-4620-b719-0e3263bef1a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'selectedOrg' and @type = 'text' and @placeholder = 'ادخل اسم المنظمة']</value>
      <webElementGuid>f5de561f-d0ca-49ff-b997-99b9acf1ac17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
