<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Label_label</name>
   <tag></tag>
   <elementGuidId>f3f3123c-1043-4b01-bf32-7a6b43e95d38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#label</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f385fdc9-5d2b-4aa8-b55c-15b50676e765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>penta-textbox</value>
      <webElementGuid>4fc07763-7ec2-4d5e-848c-ac9aa34497fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>e2c1935b-f6d6-48e7-b4e9-bc3e08dbffb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>77d8691b-4dfe-4b46-bd23-4fdcf5ae50ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;label&quot;)</value>
      <webElementGuid>18023e36-6f2e-4901-aa36-7c78e42ead27</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='label']</value>
      <webElementGuid>fe5ac444-974f-4df0-95c1-5c626360f8fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div[2]/div/div[2]/div/div[2]/div/section/aside/div/div[2]/div/div/div/div[3]/input</value>
      <webElementGuid>8cc00668-9fb7-4c91-a64b-1c3de1a4a601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>f5ea8815-c092-4c84-aab5-4a3352e3e62a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'label' and @type = 'text']</value>
      <webElementGuid>e2ddb106-1845-4bc2-a1c2-a00ea1af145d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
