<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mna Key_mnaKey</name>
   <tag></tag>
   <elementGuidId>01be0b5a-f4c8-4a1a-97bf-d05e06b6da50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mnaKey</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mnaKey']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#mnaKey</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>734a2317-dcc0-49a6-910e-4502336b1c79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>956496ca-afbe-4812-ba26-38befa7ab3c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>penta-editable-textbox</value>
      <webElementGuid>98ab1886-4a29-4578-b08a-f11c3c9000b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mnaKey</value>
      <webElementGuid>0919587d-e4e4-4a46-abe8-4ff57ef6d382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mnaKey</value>
      <webElementGuid>f2aef27d-eb88-4224-a8f6-811f0584012f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>b54a01a1-0739-46cd-80dd-7eb4e8386f04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>text3</value>
      <webElementGuid>18558f85-748a-4b19-b5f4-636cf2c55562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mnaKey&quot;)</value>
      <webElementGuid>1fe52d4d-f7c1-493c-a92f-5df875201ab9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mnaKey']</value>
      <webElementGuid>7ffd6a10-534d-4a70-bdd6-3edfc4774bfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div[2]/div/div[2]/div/div[2]/div/section/aside/div/div[2]/div/div/div/div/div[2]/input</value>
      <webElementGuid>d2d777dd-19d5-4ac4-8fe2-4742097ff431</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/input</value>
      <webElementGuid>caa296f5-c4ae-422c-8376-6c5900fc5579</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'mnaKey' and @name = 'mnaKey']</value>
      <webElementGuid>45b35a29-dd8c-4808-a166-1e7f28ccee38</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
