<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_number3(number) unique(text)</name>
   <tag></tag>
   <elementGuidId>0c58e189-0290-4bb6-9375-12d220f7462d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#parent</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='parent']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#parent</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b281b73d-281a-4b64-a722-5f7bb6415f63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>penta-textbox  penta-dropdown</value>
      <webElementGuid>1252bb3b-d586-48f7-a841-7d39c2d583f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>parent</value>
      <webElementGuid>015b2665-9e71-44aa-afe3-dd88f5b08bdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>number3(number) unique(text) </value>
      <webElementGuid>ad496b45-fe1c-4012-8ffd-fef397430f39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;parent&quot;)</value>
      <webElementGuid>accb456d-73b5-4693-8aa6-2bbd4c028f52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='parent']</value>
      <webElementGuid>d18d2600-61bf-4b1d-b2b4-82dc5e12e813</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div[2]/div/div[2]/div/div[2]/div/section/aside/div/div[2]/div/div/div/div[8]/select</value>
      <webElementGuid>b4d01455-7e07-409d-bf57-452267ffa7e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='parent'])[1]/following::select[1]</value>
      <webElementGuid>366b17b5-0c91-4af2-8d09-4a5d794c86ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Normal'])[1]/following::select[1]</value>
      <webElementGuid>abc2796a-6db8-4496-ac86-b3ed7070c003</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='condition'])[1]/preceding::select[1]</value>
      <webElementGuid>4c3b01d2-5188-4661-a667-5d43bfa8aaa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Placeholder'])[1]/preceding::select[1]</value>
      <webElementGuid>149e6f7b-dedc-4c6a-ba49-b2fa1881075f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>0ce78f2b-3951-4740-83b7-e692dbe061a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'parent' and (text() = 'number3(number) unique(text) ' or . = 'number3(number) unique(text) ')]</value>
      <webElementGuid>8317f691-110c-4aee-aa36-c7e7bc5aaf9e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
