<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Text33 - Text</name>
   <tag></tag>
   <elementGuidId>d8fafd4b-7588-4b11-a746-59c7d26c8633</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.customNode-module__custom-node__ltr-content--xhekg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/main/div[2]/div/div[2]/div/div[2]/div/section/aside/div/div[2]/div/div/div/div/div/div/div[2]/div[2]/div/div/div[2]/div/p/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Text33 - Text&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>dc2772d7-3aa0-45db-b16e-f9f2dae0bba2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>customNode-module__custom-node__ltr-content--xhekg</value>
      <webElementGuid>432bb43c-b556-46a4-93b9-a8768af28f4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Text33 - Text</value>
      <webElementGuid>ae9ebaa3-58a8-470f-9b3a-60cc617c034c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App d-flex flex-column&quot;]/main[@class=&quot;layout_layout-container__SwD1Y&quot;]/div[@class=&quot;layout_layout-children-container__mgIlz&quot;]/div[1]/div[@class=&quot;formBuilder_task-form-designer-container__8Of5A&quot;]/div[@class=&quot;sharedCollapsibleContainer_collapsible-container__rQGxR
            CollapsibleContainer-module__collapsibleDivContainer--BLS45
            CollapsibleContainer-module__collapsibleDivContainerDefault--Pf8iZ&quot;]/div[@class=&quot;CollapsibleContainer-module__collapsibleActive--_jdwW sharedCollapsibleContainer_collapsible-active__xNKbM&quot;]/div[@class=&quot;sharedCollapsibleContainer_container__U9ZIQ&quot;]/section[@class=&quot;undefined layout-module__layout--X_ghC&quot;]/aside[@class=&quot;layout-module__layout__controller--DWU0n layout-module__global-styles--QBg5e&quot;]/div[@class=&quot;container-module__container--s5FMn container-module__container--column--_uXCG controller-module__controller--V_jZ4&quot;]/div[@class=&quot;container-module__container__body--ocDRC controller-module__controller__body--ryb2H&quot;]/div[@class=&quot;controllerBody-module__controller-body--RJ39V&quot;]/div[@class=&quot;rst__tree controllerBody-module__controller-body__tree--Ug_Cg&quot;]/div[1]/div[@class=&quot;ReactVirtualized__Grid ReactVirtualized__List rst__virtualScrollOverride&quot;]/div[@class=&quot;ReactVirtualized__Grid__innerScrollContainer&quot;]/div[@class=&quot;rst__node&quot;]/div[@class=&quot;rst__nodeContent&quot;]/div[2]/div[@class=&quot;customNode-module__custom-node--ruUlE custom-node&quot;]/div[@class=&quot;customNode-module__custom-node__node-container--bXDhE&quot;]/div[@class=&quot;customNode-module__custom-node__node-body--GBHQF&quot;]/div[@class=&quot;customNode-module__custom-node__node-body-content--NPW2V&quot;]/p[@class=&quot;customNode-module__custom-node__title-text--MpRFY&quot;]/span[@class=&quot;customNode-module__custom-node__ltr-content--xhekg&quot;]</value>
      <webElementGuid>67eeb35f-5914-4b76-b13e-5d5155cda134</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div[2]/div/div[2]/div/div[2]/div/section/aside/div/div[2]/div/div/div/div/div/div/div[2]/div[2]/div/div/div[2]/div/p/span</value>
      <webElementGuid>231fc5e6-2af4-44cf-872b-69bcf6971d55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Controller'])[1]/following::span[2]</value>
      <webElementGuid>54fb6f19-8c58-46f1-8850-aa699071f031</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Integer Number'])[1]/following::span[2]</value>
      <webElementGuid>846477ca-73e6-430b-a1dd-b030e7ff19bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Text33']/parent::*</value>
      <webElementGuid>408a1bc8-4526-4ee9-b3a8-7c1d375dc7c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/span</value>
      <webElementGuid>8d17fb45-f8b1-4168-96e8-df48695c9083</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Text33 - Text' or . = 'Text33 - Text')]</value>
      <webElementGuid>159d607f-2f78-4b1d-9c7d-eb6b96c8cb36</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
