<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Plugins</name>
   <tag></tag>
   <elementGuidId>71d691a3-1f46-44db-bd2d-0894839c3e91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='common-nav__link-contrib-plugin-catalogue']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#common-nav__link-contrib-plugin-catalogue</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Plugins&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a7ddbf7a-7567-4269-90f7-b2559597d093</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-current</name>
      <type>Main</type>
      <value>page</value>
      <webElementGuid>ab7cdc42-4e00-4eab-8fcc-41839f423171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item MobileNav_dropdown-item__05t37 MobileNav_active__PhFfL</value>
      <webElementGuid>ee3d7be1-4fd6-4247-8079-c997f05c6d26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>common-nav__link-contrib-plugin-catalogue</value>
      <webElementGuid>bdc50f8c-fa8f-4d8c-b3f6-9e4147a4a0fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/penta-app-admin-entry-point-fb/MnA-fb/MyContributionsPlugins</value>
      <webElementGuid>42db2617-3fb7-49fd-9c5b-6707641afd86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Plugins</value>
      <webElementGuid>8237c7fe-d81f-493f-a8eb-1096a1dc381d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;common-nav__link-contrib-plugin-catalogue&quot;)</value>
      <webElementGuid>3b3c2e16-0236-4cbe-b2ec-36b3a25578ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='common-nav__link-contrib-plugin-catalogue']</value>
      <webElementGuid>99e02af5-f99d-4e70-8851-40f0567683f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarSupportedContent']/div/ul/li[5]/ul/a</value>
      <webElementGuid>3dff8946-6322-47ef-be9b-426d9df98d6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Plugins')])[2]</value>
      <webElementGuid>5c38e9c5-2eef-45bd-9798-1bcd04b22fb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Contributions'])[1]/following::a[1]</value>
      <webElementGuid>87b6cfa9-71be-4b82-9aef-9d18c9072c02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Applications Catalogue'])[1]/following::a[2]</value>
      <webElementGuid>fba2d324-1b6b-4403-94ec-6ae4169bfce3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Applications'])[1]/preceding::a[1]</value>
      <webElementGuid>35481fb7-58f1-451b-85a8-defd8c58a029</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sheets'])[2]/preceding::a[2]</value>
      <webElementGuid>8d4385f1-63f5-46dc-911f-743186542d6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/penta-app-admin-entry-point-fb/MnA-fb/MyContributionsPlugins')]</value>
      <webElementGuid>37cd90c9-3384-4fff-8d97-1d92305d3512</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/ul/a</value>
      <webElementGuid>c57e32e8-f262-4e09-a391-75bb6f9e3a74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'common-nav__link-contrib-plugin-catalogue' and @href = '/penta-app-admin-entry-point-fb/MnA-fb/MyContributionsPlugins' and (text() = 'Plugins' or . = 'Plugins')]</value>
      <webElementGuid>22ef132b-0da0-4f2e-b407-bf099b1f5453</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
