<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Hossam Fb</name>
   <tag></tag>
   <elementGuidId>4a9f093e-df1e-457c-957e-5332fc9590e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.CardTitle_title__Ai3Ul.CardTitle_clickable__u59M1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div[2]/div[2]/div/div/a/div[2]/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Hossam Fb&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d5e364da-243e-42d7-ae79-b80cd187f430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>CardTitle_title__Ai3Ul CardTitle_clickable__u59M1</value>
      <webElementGuid>1a9027ba-6875-4fdc-bdb8-55792730d0fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tip</name>
      <type>Main</type>
      <value>Hossam Fb</value>
      <webElementGuid>4ee52cce-3e1e-4c2e-9b25-e1363e361585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/penta-app-admin-entry-point-fb/MnA-fb/PluginPreview/e32309e1-559e-41a7-8eee-9820c2a60923/Hossam%20Fb</value>
      <webElementGuid>96ed66a4-04ea-4488-bbec-5f98a88a4e4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>currentitem</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>60cf3128-104d-47d8-ae33-f379feeb0a27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tb4f06691-8824-4468-b799-08fb7d30f1f6</value>
      <webElementGuid>23e14858-166c-4f2a-910c-68fa1d08156a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hossam Fb</value>
      <webElementGuid>2a615810-d0c4-4578-9c41-399df6ed1b77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App d-flex flex-column&quot;]/div[@class=&quot;container CatalogPage_page__9FiW- undefined&quot;]/div[@class=&quot;d-flex flex-column gap-3&quot;]/div[@class=&quot;d-flex gap-3 flex-wrap&quot;]/div[@class=&quot;PublicCatalogBase_global-card__aqymy&quot;]/div[@class=&quot;GridCard_card__+UFjt  d-flex p-3 flex-column&quot;]/a[@class=&quot;GridCard_card-link__2bLqw d-flex gap-3 flex-column flex-grow-1&quot;]/div[@class=&quot;GridCard_body__gcCxG&quot;]/div[@class=&quot;d-flex gap-2 justify-content-between&quot;]/div[@class=&quot;CardTitle_title-container__J2rZu&quot;]/a[@class=&quot;CardTitle_title__Ai3Ul CardTitle_clickable__u59M1&quot;]</value>
      <webElementGuid>27f8d690-90a8-42b3-9871-63b0163ca722</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div[2]/div/div/a/div[2]/div/div/a</value>
      <webElementGuid>f0b01e23-5797-436a-989e-d17eb8a45935</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Hossam Fb')]</value>
      <webElementGuid>93ef0f88-334e-4d94-9a68-c9a534da3a96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='How to create a plugin'])[1]/following::a[2]</value>
      <webElementGuid>3235ea2f-bd5f-4345-b2a5-2ebb1f6385bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hossam_Plugin'])[1]/preceding::a[1]</value>
      <webElementGuid>7f156a6c-bed4-4919-be13-8bc1af6a7713</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ar'])[1]/preceding::a[1]</value>
      <webElementGuid>6fb55247-e24d-4479-babc-b974af5961d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hossam Fb']/parent::*</value>
      <webElementGuid>feabe3c8-f0b0-4983-8698-e48d9b117374</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/penta-app-admin-entry-point-fb/MnA-fb/PluginPreview/e32309e1-559e-41a7-8eee-9820c2a60923/Hossam%20Fb')]</value>
      <webElementGuid>f204519d-8e76-4bd5-bea6-07d78648f0e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div[2]/div/div/a</value>
      <webElementGuid>f5fa2b5a-0498-4ec9-9340-645e5cc91614</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/penta-app-admin-entry-point-fb/MnA-fb/PluginPreview/e32309e1-559e-41a7-8eee-9820c2a60923/Hossam%20Fb' and (text() = 'Hossam Fb' or . = 'Hossam Fb')]</value>
      <webElementGuid>ed719913-0e8c-48c8-a52d-85c3258316b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
