<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_one</name>
   <tag></tag>
   <elementGuidId>0858e426-d0f2-4a04-b957-e30e73f2f582</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#collapseProcesses > div.card-body > div.card > #headingThree > div.title-collapse > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='headingThree']/div/span)[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;one&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d2217dba-69b5-42df-a032-c1ba43d34006</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>one</value>
      <webElementGuid>08e0c90f-40ce-4a38-b803-770940846782</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collapseProcesses&quot;)/div[@class=&quot;card-body&quot;]/div[@class=&quot;card&quot;]/div[@id=&quot;headingThree&quot;]/div[@class=&quot;title-collapse&quot;]/span[1]</value>
      <webElementGuid>9fbdc82b-77b2-4c6a-bda5-b5f8beba1fc3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='headingThree']/div/span)[4]</value>
      <webElementGuid>135592e0-de89-4035-a9b0-062a2adbb488</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Process'])[1]/following::span[1]</value>
      <webElementGuid>8c49880a-84d1-4f8d-9b00-4f12f8c2bc9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Orders'])[1]/following::span[2]</value>
      <webElementGuid>43ce676b-8908-4b7f-99b1-9e5d3254f261</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='islam process'])[1]/preceding::span[1]</value>
      <webElementGuid>141aea07-f19e-4fdf-8d33-3b0642adb026</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Advanced Search'])[1]/preceding::span[2]</value>
      <webElementGuid>b70ef53e-aa57-4793-87d1-2f95bbfd0b80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='one']/parent::*</value>
      <webElementGuid>f2244e14-ece9-4354-bc17-c823a5cbcf52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div/div/span</value>
      <webElementGuid>6f9a9689-57b6-42c9-be47-ba183b2c1bf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'one' or . = 'one')]</value>
      <webElementGuid>0f4af2c1-a46e-4e57-9824-0e426007ff3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
